#* If the theme set background should be shown, set to False if you want terminal background transparency.
theme_background = false

#* Automatically save current settings to config file on exit.
save_config_on_exit = false
