theme = "everforest_dark_no_bg"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
cursorline = true
completion-trigger-len = 1
scroll-lines = 1

[editor.whitespace.render]
newline = "all"

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]

left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.normal.t]
j = "rotate_view"
k = "rotate_view_reverse"
h = ":buffer-previous"
l = ":buffer-next"

n = ":new"

s = ":vsplit"
S = ":vsplit-new"
i = ":hsplit"
I = ":hsplit-new"

[keys.normal]

"$" = "goto_line_end"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
G = "goto_file_end"

[keys.select]
"$" = "goto_line_end"
G = "goto_file_end"
