#!/bin/bash

if [ -z "$ANDROID_HOME" ]; then
  echo "please set ANDROID_HOME environment variable"
  exit 255
fi
if ! [ -x "$ANDROID_HOME/platform-tools/adb" ]; then
  echo "$ANDROID_HOME/platform-tools/adb not found"
  echo "please install android-sdk to '$ANDROID_HOME'"
fi

"$ANDROID_HOME/platform-tools/adb" $@
