#!/bin/bash

if [ -z "$EMSDK" ]; then
  echo "please set EMSDK environment variable, should be sourced from ~/.bashrc"
  exit 255
fi
if ! [ -x "$EMSDK/emsdk" ]; then
  echo "$EMSDK/emsdk not found"
  echo "please install emsdk to '$EMSDK':"
  echo "  git clone https://github.com/emscripten-core/emsdk.git '$EMSDK'"
  echo 'about emscripten: https://emscripten.org'
  exit 255
fi

if [ "$1" = "shell" ]; then
  echo "entering env with emsdk..."
  source "$EMSDK/emsdk_env.sh"
  export PATH="$EMSDK/upstream/emscripten/:$PATH"
  export PATH="$EMSDK/upstream/bin/:$PATH"
  export ADVANCE_SHELL_STACK=0
  bash
else
  echo "========================================"
  echo "to enter env with emsdk: $0 shell"
  echo "========================================"
  "$EMSDK/emsdk" $@
fi
